### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/whynot.earth#1]
probably copy the university site, just need to fill content holes. This will be a marketing heavy task, as we need to figure out what we are going say about ourselves.

**Comment by paulchrisluke** [comment]
home page looking great, comments added to figma file  https://www.figma.com/file/M3U8SfOgvNiPkRHPBooBtcGQ/Why-Not-Earth?node-id=0%3A1

**Comment by paulchrisluke** [comment]
https://res.cloudinary.com/whynotearth/image/upload/v1562651584/5b_qnkog2.png
https://res.cloudinary.com/whynotearth/image/upload/v1562651585/3_ltyll1.png
https://res.cloudinary.com/whynotearth/image/upload/v1562651585/2_glqsw6.png
https://res.cloudinary.com/whynotearth/image/upload/v1562651585/meredith_smmoxu.png
https://res.cloudinary.com/whynotearth/image/upload/v1562651586/4_rendb4.png
https://res.cloudinary.com/whynotearth/image/upload/v1562651586/1b_xpy1xd.png
https://res.cloudinary.com/whynotearth/image/upload/v1562651585/meredith_hatched_qbsn0d.svg

**Comment by atharva3010** [comment]
Great, working on it.

**Comment by paulchrisluke** [comment]
https://res.cloudinary.com/whynotearth/image/upload/v1562682609/6_xbypzd.png
https://res.cloudinary.com/whynotearth/image/upload/v1562682609/7_oljhke.png
https://res.cloudinary.com/whynotearth/image/upload/v1562682609/5_yk3ubw.png
https://res.cloudinary.com/whynotearth/image/upload/v1562682609/2_ppqnz4.png
https://res.cloudinary.com/whynotearth/image/upload/v1562682607/meredith_hatched_mqzsuu.svg
https://res.cloudinary.com/whynotearth/image/upload/v1562682608/4_phriye.png
https://res.cloudinary.com/whynotearth/image/upload/v1562682608/3_w15w82.png
https://res.cloudinary.com/whynotearth/image/upload/v1562682608/1b_ddwcio.png
https://res.cloudinary.com/whynotearth/image/upload/v1562682608/demo_i9sac9.png
https://res.cloudinary.com/whynotearth/image/upload/v1562682607/meredith_fkpe6f.png

**Comment by atharva3010** [comment]
WIP

**Comment by atharva3010** [comment]
home page done, parallax on mobile view has some bugs on it, working on them.

**Comment by paulchrisluke** [comment]
tighten up the copy section in hero to match design. Less margin between items, and smaller width

![image](https://user-images.githubusercontent.com/5694308/61124161-64a1f800-a4d0-11e9-8b02-725ec12e4fda.png)

**Comment by atharva3010** [comment]
done
