### ISSUE TITLE
Set up Drip for outbound marketing

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/whynot.earth#11]
We need to set up the drip api (see https://developer.drip.com/) as it will be used in the implementation of a newsletter service triggered to all subscribers on each blog post submission, the submissions will be done via CMS.

**Comment by paulchrisluke** [comment]
We may be moving to something other than drip. They are really just fancy triggering... may be able to set similar up using sendgrid or mailgun... Ping me before we start looking into this and make sure we decide on a good platform to use
