### ISSUE TITLE
[UX] setup volkswagon pitch 2.0

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/whynot.earth#13]
```
Hey Chris,

 Thanks for discussing next steps for the HTML-based JumpStart.

Attached are a few of the branding elements you can incorporate into the presentation to make it a little more customized. The designer is out right now so unfortunately all I have are the screenshot samples, but hopefully you can just do a little crop, copy and paste action.

Additionally, I’ve provided a few samples of the JumpStart. I’ve intentionally provided some that are a bit longer in length to demonstrate the issues we have with content limitation control – we need these newsletters to be shaved down to a page ideally, with the ABILITY to see “attachments” or additional content elsewhere (redirect to site). This would eventually serve as training for content submitters to shorten the entries entirely. Some things, for instance a letter from the CEO, or perhaps a policy update, would need to be longer in length, but it would be ideal to shave this stuff down to a twitter length at the maximum so people aren’t being overloaded with content that isn’t relevant or important.

Again, some of the things we discussed today that would be beneficial to see in a presentation would be the following:

·         Site/email look and feel
·         User roles and approval process
·         Administrative access from any device, any time
·         Print functions
·         Video support capabilities
·         Email syncing, or how we could load the emails/distribution lists into the system
·         Tracking and metrics example
 
Again, the presentation wouldn’t need to be anything crazy, even a powerpoint or something could work. I haven’t had a chance to review the progressive web app video, as I’m about to run to another meeting, but if there’s anything in there you think could be beneficial, feel free to incorporate.

Let me know if you have any questions! Feel free to just contact however.
```
[JumpStart. Aug. 1, 2019.pdf](https://github.com/whynotearth/whynot.earth/files/3468459/JumpStart.Aug.1.2019.pdf)
[JumpStart. Aug. 5, 2019.pdf](https://github.com/whynotearth/whynot.earth/files/3468460/JumpStart.Aug.5.2019.pdf)
[JumpStart. July 22, 2019.pdf](
![201_NewJumpsStartLogos](https://user-images.githubusercontent.com/5694308/62478966-9f990200-b7d6-11e9-85ce-c666a76efd1d.jpg)
https://github.com/whynotearth/whynot.earth/files/3468461/JumpStart.July.22.2019.pdf)
[JumpStart. July 16, 2019.pdf](https://github.com/whynotearth/whynot.earth/files/3468462/JumpStart.July.16.2019.pdf)
![JumpStart logo test](https://user-images.githubusercontent.com/5694308/62478871-5fd21a80-b7d6-11e9-99f4-83287830087d.JPG)

We don't actually need to do a full prototype with interactions by tomorrow. A simple powerpoint will do as long as we can show jpg's of our ux according to what he's looking for.

**Comment by bamboochow** [comment]
@paulchrisluke are you handling the email loading/tracking and metrics?

**Comment by paulchrisluke** [comment]
email loading is going to be "add to category" 

- email@dist.1 (announcements)
- email@dist.2 (events)
- email@dist.3 (health)

and yea I'll think of tracking and metrics... perhaps just copy medium.com tracking?

https://medium.com/me/stats
![image](https://user-images.githubusercontent.com/5694308/62480340-c6a50300-b7d9-11e9-8ad2-0404d55d506f.png)
![image](https://user-images.githubusercontent.com/5694308/62480370-d886a600-b7d9-11e9-8583-64bfef2de532.png)

**Comment by paulchrisluke** [comment]
Please power point today each slide should have these titles

·         Site/email look and feel
here we want to show my example of email talk about the fact that we made it white for easier printing that it's a one pager with easy access to other attachments on going. Talk about how we wanted to make it modular allowing for all sorts of different content to fit within the same template. Also talked about how this site will build a corresponding progressive web app website which holds all content and is indexibke with google

·         User roles and approval process

this can just show a couple screenshots of that process with a simple bullet point is says users can have admin editor and approval roles

·         Administrative access from any device, any time

Easy slide just literally right that line with a screenshot of our stuff on a phone

·         Print functions

To show a print button and a demo of what it would look like printed out

·         Video support capabilities
Because this is an HTML5 site all posts witch have video content can support video playback on site

·         Email syncing, or how we could load the emails/distribution lists into the system
Just say supports contact loading out of the box, and can integrate with your custom email solution via are open source rest API


·         Tracking and metrics example
just show a screenshot of mediums metrics you can also look at drip.com or MailChimp they're reporting... That should be the same metrics that Volkswagen would want
