### ISSUE TITLE
Add banner to site

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/whynot.earth#27]
We want to add banners with an animated egg falling into the site to add interactivity with site visitors
![image](https://user-images.githubusercontent.com/5694308/67832261-a7d1b680-fb13-11e9-929f-510064da91d4.png)

The egg asset should be animated falling through banner (falling controlled by scroll speed) as you scroll down the page and crack when it hits the bottom. 

Reference for placement here: 
![image](https://user-images.githubusercontent.com/5694308/67832309-d51e6480-fb13-11e9-900e-7f459ab396f6.png)
This banner is the first on in this image 

The lower banner will be our universal footer, tasked out in #38 . 

Design file here for reference: 
https://www.figma.com/file/M3U8SfOgvNiPkRHPBooBtcGQ/Why-Not-Earth?node-id=482%3A196

**Comment by paulchrisluke** [comment]
We may want to do a lottie animation for this or parralax... I wonder what is best? @mort3za ?  @atharva3010

**Comment by mort3za** [comment]
Parallax effect can't be used alone I think, because the egg needs to be cracked and not just move. This medium article has a sample of doing such animations by lottie, TweenMax and scrollMagic: https://uxplanet.org/the-ultimate-workflow-of-creating-scroll-based-animations-7366b670630
