### ISSUE TITLE
Create Career Page with Typeform Integration

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/whynot.earth#36]
This is a sample page of an individual career page for the why not earth site. Design wise, here is what we're thinking: 

Here is the complete design of this page 
![image](https://user-images.githubusercontent.com/5694308/68003938-1d6b8d00-fca2-11e9-9af5-b20f4853324a.png)

The top has a top nav that's already created (will write separate issue to update top nav) 
![image](https://user-images.githubusercontent.com/5694308/68003285-36267380-fc9f-11e9-81cd-f17b673bd740.png)
It also has a full size header image, use any placeholder for now, around 400 px height, can adjust depending on images but stay there for now 

![image](https://user-images.githubusercontent.com/5694308/68003350-8ef60c00-fc9f-11e9-9ef9-1f2441efd31e.png)
Page title in H1, subtitle in H2

Page Content: 
Our primary product is our .net api, meredith-core. She was originally piloted as a software I built for my previous company, a large marketing agency. We had 15 clients, all with large amounts of ad spend and users coming through multiple unique landing pages per day. I needed a way to figure out how to produce thousands of unique landing pages, linked with the correct data tracking, and conversion metrics, all with a small team of 3 devs. Terri was born. Meredith-core is an opensource and different take on that approach. She builds custom web apps with intergrations with stripe, google, facebook, and all most other thigns businesses need to run an effective marketing campaign and webapp online. Always opensource and maintained, our goal is to make a useful marketing engine, comparable to the enterprise level software I built before, but for medium/small businesses and opensource.

Your role would be to manage the creation of endpoints to connect data inserted via our CMS into our postgres database and vice verse. Integrations with various marketing API's like facebook and google are also possible, at various experience levels.

Our .net maintainer is active in discord and git, and always available for questions.

Experience Preferences:

Junior developers are always welcome in any of our projects. But arguably our .net work is less well documented than our front end stuff. If you are looking for a way to learn how to integrate into a team, be reliable, understand core concepts and learn from a stellar backend mentor group, this is a good opportunity. However, we hold everyone on our team to a high standard. High code quality is not as expected as realability and work ethic, we can train the other stuff.

Intermediate/Advanced developers are probably preferred. They will be able to take higher level concepts like "give me all the data you can out of the google ads api and drop it into postgres" and break that down into actionable tasks with less need to be guided at every step. We understand our intermediate to advanced developers time is valuable, and hope to show that our projects are interesting and being used for the greater good. We support nonprofits in developing countries, opensource everything we do, and our software has been featured in case studies by Cloudflare, and Google. I try to foster a small but smart group of talented developers, and use our opensource contributions as a way to find new hires. To date, every developer that has regularily commited to our projects has been paid. While this is not a guarantee of paid work, it is nice to see how well you fit in our team dynamic and usefulness before committing to a full time hire.

Look forward to working with you!

Love, Chris Luke

Use default paragraph text in body for now, will update fonts in font issue later 

![image](https://user-images.githubusercontent.com/5694308/68003410-cebcf380-fc9f-11e9-9bab-48cfcd3d9344.png)
Typeform embedding in this section: 
```
<div class="typeform-widget" data-url="https://paulchrisluke.typeform.com/to/TNDX88" data-transparency="50" style="width: 100%; height: 500px;"></div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> <div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"> powered by <a href="https://admin.typeform.com/signup?utm_campaign=TNDX88&utm_source=typeform.com-14889424-Free&utm_medium=typeform&utm_content=typeform-embedded-poweredbytypeform&utm_term=EN" style="color: #999" target="_blank">Typeform</a> </div>
```

![image](https://user-images.githubusercontent.com/5694308/68003803-8f8fa200-fca1-11e9-8844-d8d777f82bd8.png)
For the "see more" use the same visual setup as Shinta Mani Wild's small search cards: Image, title (Normal font), Description (small font), can use lorem ipsum and place holders for now  

Footer will be changed in separate issue: use what we have for now

**Comment by paulchrisluke** [comment]
@mort3za 
![image](https://user-images.githubusercontent.com/5694308/68847484-5b849a00-0701-11ea-9e7b-44c4d40ad634.png)
Can you connect these items to the api, pulling career pages? 
Name: career   CategoryId: 11

![image](https://user-images.githubusercontent.com/5694308/68847697-a56d8000-0701-11ea-96aa-0c396aca8960.png)
Similar to how these career pages were pulled from the api, we want to see each individual career page suggested as "explore career"

**Comment by mort3za** [comment]
Testing email reply by chmail.ir

by Morteza

​​​​

**Comment by mort3za** [comment]
Hey Chris

I know it's a weird way for sending a message but internet is fully shutdown in Iran 🤷‍♂️

Here people are protesting and Internet is shutdown by government because of security concerns.

I just wanted to let you know about it.

I don't know when internet is back again sadly.

you have my mobile number and this is my temporary email address: mort3za@chmail.ir

- sending this email by an "interanet" service, seems work.

If you get this message, send me your email address so I can contact you.

Please remove this message from github. 

Thank you and sorry for the issue


​​​​

**Comment by paulchrisluke** [comment]
I’m sorry to hear this. Take your time, no pressure on work. I’m still
working on paperwork for you to come back out here.
