### ISSUE TITLE
enable single user tracking

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/whynot.earth#45]
Just like we did before, please enable clientID tracking for whynot.earth. If you need access, please give me your email and I will grant it to you

**Comment by Mako1994** [comment]
sorry Chris for being away for a while.
I will setup the single user tracking this week.

Can you add makototennis@gmail.com
 to whynot.earth, Google analytics and Google Tag Manager?

**Comment by Mako1994** [comment]
hey, Chris.
Let me know when you can add my email address to the GTM and GA so that I can set up.
I am available this entire week :)

**Comment by paulchrisluke** [comment]
Just sent you an invite for both, you should have access now.

**Comment by Mako1994** [comment]
Thank you!
Shall be able to set up within today.
Will have the code to be placed on the website once other steps are completed.

**Comment by Mako1994** [comment]
<img width="1365" alt="Screen Shot 2019-11-23 at 4 38 55 PM" src="https://user-images.githubusercontent.com/53460469/69475412-13a3f800-0e10-11ea-9842-9526df76b16a.png">
<img width="1364" alt="Screen Shot 2019-11-23 at 4 38 37 PM" src="https://user-images.githubusercontent.com/53460469/69475413-13a3f800-0e10-11ea-929f-8d086ba69f0b.png">

hey chris, it seems I dont have full access to the GTM, I am in a "View only mode" and cannot add a new tag.
