### ISSUE TITLE
Basic Footer

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/whynot.earth#49]
What we have currently is the same as the vkirirom site 
![image](https://user-images.githubusercontent.com/5694308/68362111-ad08b400-0158-11ea-9b0e-956c480345ec.png)

We have a new issue for the actual footer we want #38 However, this is what we need for our mvp

We need to change the footer into this design: 
![image](https://user-images.githubusercontent.com/5694308/68361930-1d630580-0158-11ea-96fc-f4394b911781.png)

Each Section is 208 px apart and the entire image/text area should be centered 
![image](https://user-images.githubusercontent.com/5694308/68364036-623e6a80-015f-11ea-9a7f-2eeff6728546.png)

Design file for reference: 
https://www.figma.com/file/M3U8SfOgvNiPkRHPBooBtcGQ/Why-Not-Earth?node-id=0%3A1

**Comment by paulchrisluke** [comment]
I will add mobile footer soon. :D

**Comment by hunter-isaiah96** [comment]
Footer is updated now on the basic footer branch, however, I don't have access to the project board so I can't update the board.
